### ISSUE TITLE
Move package to an org?

### ISSUE THREAD

**Issue by ViralBShah** [yeesian/ArchGDAL.jl#143]
I am wondering if ArchGDAL.jl should be in an org. Is JuliaGeo the right place for it, or perhaps some other one? Just thought I would ask since I am seeing it show up in more places.

**Comment by ViralBShah** [comment]
Pinging @vlandau and @ranjanan since we use it in Circuitscape and Omniscape.

**Comment by yeesian** [comment]
I had this discussion with @visr (who is a co-owner of this package) and my understanding is that
1. the official/canonical package for working with GDAL is still GDAL.jl, and
2.  there is already enough happening with https://github.com/JuliaGeo/GeoInterfaceRFC.jl that I don't wish to overburden the JuliaGeo organization with the ongoing maintenance/development of this package for now.

In terms of next steps,
* If you're looking for the strongest guarantee of stability/etc, my recommendation is to use GDAL.jl, since it is less likely to have API churn than this package.
* I will continue to keep this package under my name until I feel comfortable with the overall functionality and feel of the API, and have corresponding documentation & tests for how it should be used. The remaining work I have in mind mostly pertains to fleshing out APIs with well-trodden workflows for (i) interacting with databases, and (ii) working with rasters and images.

We have recently completed a number of big items (#118, #105, #100, #97), and the remaining open issues are beginning to skew more towards documentation improvements, so I feel optimistic about progress towards a v1.0 release (at which point we can revisit this conversation).

**Comment by ViralBShah** [comment]
Thanks for the explanation. This does make sense. We are happy to keep up with the api changes.
