### ISSUE TITLE
How to extract GCP's from a raster?

### ISSUE THREAD

**Issue by bjoern234** [yeesian/ArchGDAL.jl#161]
Hi!
Is there a way to extract embedded Ground Control Points (GCPs) from a raster such as in Python GDAL `GetGCPs()` function?

Thanks in advance!
Bjoern

**Comment by visr** [comment]
It looks like this function has not yet been added to ArchGDAL, there are some other GCP related functions here: https://github.com/yeesian/ArchGDAL.jl/blob/40c7a2b7aea45c8116189c381626e2117f574516/src/gcp.jl.

However you can access this funcion from GDAL.jl: https://github.com/JuliaGeo/GDAL.jl/blob/ac27d0f35569a560abd813f217d90beaaf1a5f76/src/gdal_h.jl#L1149-L1156

I don't really have an example ready though. But since ArchGDAL.jl uses GDAL.jl, you can use the two together as well. If you've used the Python GDAL API, the functions are probably very similar.

**Comment by bjoern234** [comment]
Yes, you are right. With `GDAL.gdalgetgcps()` and  `Base.unsafe_load()` I'm able to access the GCP values. Thank you!
