### ISSUE TITLE
Clean up NULL / Nothing / Missing semantics

### ISSUE THREAD

**Issue by yeesian** [yeesian/ArchGDAL.jl#192]
Came up in a few places (e.g. #177) so opening this issue to make sure we have a systematic approach across the entirety of this package. See also https://discourse.julialang.org/t/whats-the-difference-between-null-na-null-nothing/6468/6.

**Comment by yeesian** [comment]
See discussion in https://github.com/yeesian/ArchGDAL.jl/pull/179#discussion_r642116029, in particular [this FAQ entry](https://docs.julialang.org/en/v1/manual/faq/#Nothingness-and-missing-values-1):

> To represent missing data in the statistical sense (NA in R or NULL in SQL), use the missing object.

As described by @visr, 

> The NULL in the example of #177 seems to represent missing data to me. Especially if we see Features as rows in a Table / records in a dataset.
>
> findfieldindex, if it was written in Julia, should probably return nothing instead of -1, like findfirst. But the index truly doesn't exist, whereas the data can be viewed as missing (the field name exists after all).

**Comment by rafaqz** [comment]
This is the most important part for me. Returning `missing` when there is no nodatavalue in a raster is not really aligned with the julia meanings of `missing` and `nothing`. There are simply no nodata values in the file at all, as opposed to some nodatavalues with the value of `missing`. This is like `findfirst` returning nothing when the value simply isn't in the searched object.

```julia
help?> nothing
search: nothing Nothing isnothing

  nothing

  The singleton instance of type Nothing, used by convention when there is no value to return (as in a C void
  function) or when a variable or field holds no value.

help?> missing
search: missing Missing missingval missingmask MissingException ismissing nonmissingtype skipmissing

  missing

  The singleton instance of type Missing representing a missing value.
```

**Comment by visr** [comment]
I agree with @rafaqz that `getnodatavalue` should return `nothing` if there is no nodata value. So in https://github.com/yeesian/ArchGDAL.jl/issues/192#issuecomment-851678784 we're not disagreeing, just talking about different functions. Per function we'll have to decide which one is more appropriate.

Actually in this commit: https://github.com/yeesian/ArchGDAL.jl/pull/179/commits/83b70259519581b1ca8070284f5c56d2f3d9e053

I would argue that `findfieldindex` should return `nothing`, because there is actually no index, whereas `getfield` should return `missing`, since the field exists for other features, it's just missing/NULL for that feature. That is what I meant with https://github.com/yeesian/ArchGDAL.jl/pull/179#discussion_r642116029.

**Comment by yeesian** [comment]
> I would argue that findfieldindex should return nothing, because there is actually no index, whereas getfield should return missing, since the field exists for other features, it's just missing/NULL for that feature.

Thanks! See https://github.com/yeesian/ArchGDAL.jl/pull/179/commits/36c59698163177579a66f1c068fb8d55b9dd654c
