### ISSUE TITLE
Simple conversion to Meshes.jl

### ISSUE THREAD

**Issue by ErickChacon** [yeesian/ArchGDAL.jl#378]
I want to convert `ArchGDAL` geometries to other types like `Meshes.jl` using `GeoInterface.jl`.

If I try to do it directly, it works without problems:

```julia
import ArchGDAL as AG
import GeoInterface as GI
using Meshes

mypoint = AG.createpoint(1.0, 2.0)
GI.coordinates(mypoint) |> Point
```

However it does not work if I try to do it using a custom function (it just hangs).

```julia
function topoint(geom)
    coords = GI.coordinates(geom)
    Point(coords)
end
topoint(mypoint)
```

Can anyone provide an insight of why it happens?

**Comment by rafaqz** [comment]
You really need an MWE showing what you run exactly and the full syack yrace of the error, or its very hard to know.

But these days we usually use `GeoInterface.convert(PackageName, object)` to convert geometries between packages, rather than the old `coordinates`. 

This works with GeometryBasics.jl, GeoInterface.jl, LibGEOS.jl, ArchGDAL.jl as sinks, and those plus Shapefile.jl, GeoJSON.jl, KML.jl and some others as sources (you can just write with those directly so converting is redundant).

Meshes.jl has not implemented this interface as far as I know, and doesnt even depend on GeoInterface.jl. I think there os another packahe that implements this somehow.

But this is not a problem with ArchGDAL.jl, but for Meshes.jl via GeoInterface.jl.

**Comment by ErickChacon** [comment]
My MWE is:

```julia
import ArchGDAL as AG
import GeoInterface as GI
using Meshes

mypoint = AG.createpoint(1.0, 5.0)

function topoint(geom)
    coords = GI.coordinates(geom)
    Meshes.Point(coords)
end

topoint(mypoint)
```

Unfortunately, I can not show the full stack trace of the error because julia hangs for ever. and Ctrl-C does not work, so I am forced to kill Julia. This same code work with other packages like `Shapefile.jl` and `GeoJSON.jl`, but does not work with ArchGDAL.

I am trying to check this basic function to help with the GeoInterface implementation for `Meshes.jl` which lives in `GeoTables.jl` (https://github.com/JuliaEarth/GeoTables.jl/blob/master/src/conversion.jl). I also open an issue in GeoTables (JuliaEarth/GeoTables.jl#13). 

I want to use something like `GeoInterface.convert`, but inside this function I can see that other packages still call `GI.coordinates`. I tried to use `GeoInterface.convert` but Julia still hangs when I call `Meshes.Point(GI.coordinates(geom))` inside any function, but only happens when geom is an `ArchGDAL` geometry. 

I will continue checking what is the root of the problem, but happy to receive any suggestion.

**Comment by ErickChacon** [comment]
I am closing this issue because it can be solved by making a constructor of `Meshes.jl` for `Vec` over `AbstractVector` type-stable (JuliaEarth/GeoTables.jl#13). Thank you so much for your help @rafaqz.
