### ISSUE TITLE
getindex methods for Dataset

### ISSUE THREAD

**Issue by rafaqz** [yeesian/ArchGDAL.jl#91]
It would be good to have a `getindex` method for Dataset as a wrapper to `read` that accepted `Integer` and `Colon` indexes, instead of only `UnitRange`.  It would also be great for standardisation if it used the same indices as the array returned by `read(ds)`, but less critical.

I've written a wrapper for ArchGDAL that is aiming to present a standard interface shared with other data sources like NCDatasets: https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/gdal.jl

It works fine for whole arrays and (kind of) for unitranges, but it's going to need a lot of special casing and a rewrite/wrapper of the `rasterio()` methods for these things to work as users will expect. Maybe that would be more useful here? I'm not sure.

**Comment by rafaqz** [comment]
I'm thinking about that a lot actually! GeoArrays seems to be using some non-standard `getindex` that wont be compatible with GeoData ( I use `select(array, Lat(Near((-20, 20))))` to index with actual latittude values, getindex is just array indices). But the transforms and affine map parts of GeoArrays are great for handling more complex projections and I'll learn a lot from what happens there.

My goal is to make as many as possible Base julia methods work as expected s copy, getindex, view, and and lots of other things like reduce/mean/min/max etc.

These also work with named dimension indexing. So we should be able to do `GDALarray(filename)[Lat(1:30), Lon(1:100), Band(1)] |> plot` and it just works and loads straight from disk without an intermediate array (I think that does already work but the plot might be upside down). `NCarray(filename)[Lat(1:30), Lon(1:100), Band(1)] |> plot` will similarly work for NCDatasets.

But this doesn't work currently: `GDALarray(filename)[Lat(1), Lon(1), Band(1)]` because of the limitations to `read` in ArchGDAL. It works for NCDatasets because CFVariable is an AbstractArray wrapping a pointer to the disk variable, and it defines `getindex` and similar methods. Maybe ArchGDAL could do something like that to abstract away `read` and present an array interface over the data.

**Comment by evetion** [comment]
> GDALarray(filename)[Lat(1:30), Lon(1:100), Band(1)]

In GeoArrays I've actually have tried the same thing, but haven't implemented it fully like you're trying now. It only works with direct coordinate indexing for now (on `Float64`).

```julia
julia> fn = joinpath(dirname(pathof(GeoArrays)), "..", "test/data/utmsmall.tif")
julia> ga = GeoArrays.read(fn)
julia> ga[445700.0, 3.75126e6]
1-element Array{UInt8,1}:
 0xef
```
But I will have a look at also overloading for the `StepRangeLen` types (those resulting from `Colon :` operators.

However, because indexing with floats is "unknown" behaviour, we should document very well what it does. For example, Your `Lat(1:30)` could be interpreted not as requesting values in between (1 <= lat <= 30), but also (more logical in my opinion) as requesting values at each stepsize (it expands to `1:1:30`), resulting in a new interpolated `Array` with length 30.

For your use case I would propose something along the way of https://github.com/andyferris/AcceleratedArrays.jl#intervals, use an Interval defined as `1..30` which can be used to filter.

**Comment by rafaqz** [comment]
`A[Lat(1.30)]` is actually `A[:, 1:30]` with colons to fill missing dims. Lat just marks the dimension so index order doesnt matter (which has some very useful consequences). Same for view. I think getindex should allways mean get-index or we lose the usefullness of named indexing.

`select(a, Lat<|Between(a, b))` is treating Lat as an actual lattitide. Lat<|Near(1:30) would do what you describe.
